### ISSUE TITLE
New dev here, help needed 

### ISSUE THREAD

**Issue by anantdevcs** [OmarAlesharie/Fighting-Survival#1]
Hi! 
Can you give pointers on how to run this project locally on unity editor
Right now, I have opened the  unity project in the editor but there is no currently active scene.
Thanks!
![image](https://user-images.githubusercontent.com/44704124/171572479-1ef65cc1-0058-40ac-9136-b869ee4e8716.png)

**Comment by OmarAlesharie** [comment]
Hi

I developed this project long time ago, and I don't have Unity installed
If you're not in a hurry I'll check it later

**Comment by anantdevcs** [comment]
Hi!
No worries just got it working
Thanks for reaching out btw :)
